name: upload-sfca

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.SF_AUTH }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias dxvizdev

      - name: Verify Login
        run: |
          sf org display --target-org dxvizdev

      - name: Upload SFCA Results
        run: |
          node load-sfca.js
