name: SFCA Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:

  sfca-analysis:

    runs-on: ubuntu-latest

    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME: ${{ github.ref_name }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt

          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias SFCA

      - name: Verify Org
        run: |
          sf org display --target-org SFCA

      - name: Deploy Salesforce Metadata
        run: |
          sf project deploy start \
            --target-org SFCA \
            --source-dir force-app

      - name: Install Salesforce Code Analyzer
        run: |
          echo y | sf plugins install @salesforce/sfdx-scanner

      - name: Run SFCA
        run: |
          sf scanner run \
            --target force-app \
            --format json \
            --outfile sfca-results.json

      - name: Install Dependencies
        run: |
          npm install

      - name: Load Results To Salesforce
        run: |
          node scripts/load-sfca.js

      - name: Upload SFCA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfca-results
          path: sfca-results.json